apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gke
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke
  template:
    metadata:
      labels:
        app: gke
    spec:
      containers:
      - image: gcr.io/updater-280719/gcpdevops:latest
        name: gcp-devops-gke
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gke
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: gcp-devops-gke-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: gke
  type: LoadBalancer
